# Generated by Django 4.1.7 on 2023-03-20 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin_number', models.CharField(default='', max_length=30)),
                ('iframe', models.TextField()),
                ('iframe_with_params', models.TextField()),
                ('src', models.TextField()),
                ('src_with_params', models.TextField()),
                ('short_id', models.TextField()),
                ('privacy', models.TextField()),
                ('white_label', models.TextField()),
                ('full_screen', models.TextField()),
                ('short_url', models.TextField()),
                ('thumb', models.TextField()),
                ('fields', models.JSONField()),
                ('gallery', models.JSONField()),
                ('interior_hotspots', models.JSONField()),
                ('interior_conditions', models.JSONField()),
                ('exterior_conditions', models.JSONField()),
                ('exterior_hotspots', models.JSONField()),
                ('gallery_pics', models.JSONField()),
                ('safetyFeatures', models.JSONField()),
                ('entertainmentFeatures', models.JSONField()),
                ('luxuryFeatures', models.JSONField()),
            ],
            options={
                'db_table': 'mongo_blog',
            },
        ),
    ]
